export const typographyTokens = {
  fontFamily: {
    body: [
      "Inter",
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "sans-serif",
    ].join(","),
    editorial: 'Georgia, "Times New Roman", serif',
  },
  tracking: {
    none: 0,
    tightLabel: "0.01em",
    label: "0.08em",
    nav: "0.16em",
    wide: "0.22em",
    widest: "0.24em",
  },
  lineHeight: {
    flat: 1,
    editorialTight: 0.96,
    heading: 1.04,
    body: 1.6,
    bodyRelaxed: 1.8,
  },
  scale: {
    eyebrow: "0.72rem",
    caption: "0.75rem",
    fieldError: "0.78rem",
    fieldTitle: "0.8rem",
    button: "0.9rem",
    subheadXs: "0.98rem",
    subheadMd: "1.05rem",
    headlineXs: "2rem",
    headlineMd: "2.3rem",
    headlineLg: "3rem",
    displayXs: "2.72rem",
    displayMd: "3.55rem",
    displayLg: "4.85rem",
  },
  weight: {
    regular: 400,
    medium: 500,
    bold: 700,
    heavy: 800,
  },
} as const;
